apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mlbparks-builds
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: jbosseap
    name: jbosseap
  spec:
    tags:
    - from:
        kind: DockerImage
        name: jboss-eap70-openshift:1.7
      name: 1.7
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: eap70-basic-s2i
      application: mlbparks
      template: eap70-basic-s2i
      xpaas: 1.4.14
    name: mlbparks-pipeline
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mlbparks:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /MLBParks
      git:
        ref: master
        uri: https://github.com/SammZhu/advdev_homework.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: http://nexus3-${GUID}-nexus.apps.${CLUSTER}/repository/maven-all-public
        - name: ARTIFACT_DIR
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.7
          namespace: ${GUID}-jenkins
        incremental: true
      type: Source
    successfulBuildsHistoryLimit: 5
  status:
    lastVersion: 0
parameters:  
- description: GUID
  from: '[A-Z0-9]{8}'   
  generate: expression
  name: GUID
